# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezGLZjcP1fKwzsLBismMKKjy3ub_aRrX
"""

print("1 ,2 ,3 ,4 ,5 ,6 ,7 , 8 , 9 , 10")

numero = int(input("escreva o seu numero "))
if numero % 2 == 0:
    print("par")
else:
    print("impar")

lista = [ 1 ,2 ,3 ,4]
for elemento in lista:
    print(elemento)

numero = int(input("Digite um número: "))

while numero % 2 != 0:
    print("O número é ímpar, digite outro número:")
    numero = int(input())

print("Você digitou um número par!")

lista = [1,2,3,4,5,6,7,8,9,10]
soma = lista[0] + lista[-1]
print(f"A soma do primeiro número e do último é {soma}")

while True:
    num1 = int(input("Digite um número: "))
    num2 = int(input("Digite o segundo número: "))

    if num1 < num2:
        print("O primeiro número é menor que o segundo. Encerrando o programa.")
        break
    else:
        print("O primeiro número é maior que o segundo, digite novamente.")

pali = input("Digite uma palavra: ") .lower().strip()
pali_i = reversed(pali)
if pali == ''.join(pali_i):
    print(f"A palavra {pali} é um palíndromo")
else:
    print(f"A palavra {pali} não é um palíndromo")

num_1 = int(input("Digite o primeiro número: "))
num_2 = int(input("Digite o segundo número: "))
while num_1 = 0 and num_2 = 0:
    if num_1 > num_2:
        print("O maior número é:", num_1)

lista = [1, 2, 3, 4, 2, 4, 4, 3]
contagem = {}
for numero in lista:
    if numero in contagem:
        contagem[numero] += 1
    else:
        contagem[numero] = 1
print(contagem)